# Generated by Django 6.0.6 on 2026-06-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programschedule',
            options={'ordering': ['day_order', 'start_time']},
        ),
        migrations.AddField(
            model_name='programschedule',
            name='day_order',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
