# Generated by Django 6.0.6 on 2026-07-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, choices=[('mother_name', "What is your mother's maiden name?"), ('pet_name', 'What was the name of your first pet?'), ('school_name', 'What was the name of your primary school?'), ('city_born', 'In which city were you born?'), ('favourite_food', 'What is your favourite food?')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
