# Generated by Django 6.0.6 on 2026-06-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rj', models.CharField(max_length=100)),
                ('is_live', models.BooleanField(default=False)),
                ('stream_url', models.URLField(default='https://radio.chethanafm.com/live')),
            ],
        ),
    ]
