# Generated by Django 6.0.6 on 2026-06-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-sent_at']},
        ),
    ]
